#!/bin/sh
if [ ! -f elimai-standalone.jar ]; then
	wget -O elimai-standalone.jar https://github.com/dlokesh/elimai/releases/download/v0.1.1/elimai-0.1.1-standalone.jar
fi
drip -jar elimai-standalone.jar